[changelog]
header = "# Changelog\n"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }}{% endfor %}
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
commit_types = [
  { type = "feat",     group = "Added" },
  { type = "fix",      group = "Fixed" },
  { type = "docs",     group = "Documentation" },
  { type = "style",    group = "Style" },
  { type = "refactor", group = "Refactor" },
  { type = "perf",     group = "Performance" },
  { type = "test",     group = "Testing" },
  { type = "chore",    group = "Miscellaneous" },
]
